### ISSUE TITLE
java.lang.RuntimeException: startPreview failed

### ISSUE THREAD

**Issue by zhelin** [commonsguy/cwac-camera#219]
Samsung Galaxy Tab
Model number : GT-P3100
Android Version : 4.1.2
CWAC Version : 0.6.10

09-29 16:39:15.367: E/AndroidRuntime(4135): FATAL EXCEPTION: main
09-29 16:39:15.367: E/AndroidRuntime(4135): java.lang.RuntimeException: startPreview failed
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.hardware.Camera.startPreview(Native Method)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at com.commonsware.cwac.camera.CameraView.startPreview(CameraView.java:533)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at com.commonsware.cwac.camera.CameraView.initPreview(CameraView.java:528)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at com.commonsware.cwac.camera.CameraView.initPreview(CameraView.java:511)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at com.commonsware.cwac.camera.TexturePreviewStrategy.onSurfaceTextureAvailable(TexturePreviewStrategy.java:45)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.TextureView.getHardwareLayer(TextureView.java:368)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.View.getDisplayList(View.java:12685)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.View.getDisplayList(View.java:12760)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.View.draw(View.java:13489)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.ViewGroup.drawChild(ViewGroup.java:2940)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2810)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.View.getDisplayList(View.java:12714)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.View.getDisplayList(View.java:12760)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.View.draw(View.java:13489)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.ViewGroup.drawChild(ViewGroup.java:2940)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2810)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.View.getDisplayList(View.java:12714)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.View.getDisplayList(View.java:12760)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.View.draw(View.java:13489)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.ViewGroup.drawChild(ViewGroup.java:2940)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2810)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.View.getDisplayList(View.java:12714)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.View.getDisplayList(View.java:12760)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.View.draw(View.java:13489)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.ViewGroup.drawChild(ViewGroup.java:2940)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2810)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.View.getDisplayList(View.java:12714)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.View.getDisplayList(View.java:12760)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.View.draw(View.java:13489)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.ViewGroup.drawChild(ViewGroup.java:2940)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2810)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.View.draw(View.java:13768)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.widget.FrameLayout.draw(FrameLayout.java:467)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.View.getDisplayList(View.java:12716)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.View.getDisplayList(View.java:12760)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.View.draw(View.java:13489)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.ViewGroup.drawChild(ViewGroup.java:2940)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2810)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.View.getDisplayList(View.java:12714)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.View.getDisplayList(View.java:12760)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.View.draw(View.java:13489)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.ViewGroup.drawChild(ViewGroup.java:2940)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2810)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.View.draw(View.java:13768)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.widget.FrameLayout.draw(FrameLayout.java:467)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2394)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.View.getDisplayList(View.java:12716)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.View.getDisplayList(View.java:12760)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1144)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2267)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2139)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1950)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4464)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.Choreographer.doCallbacks(Choreographer.java:555)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.Choreographer.doFrame(Choreographer.java:525)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.os.Handler.handleCallback(Handler.java:615)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.os.Handler.dispatchMessage(Handler.java:92)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.os.Looper.loop(Looper.java:137)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at android.app.ActivityThread.main(ActivityThread.java:4895)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at java.lang.reflect.Method.invokeNative(Native Method)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at java.lang.reflect.Method.invoke(Method.java:511)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:994)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:761)
09-29 16:39:15.367: E/AndroidRuntime(4135): 	at dalvik.system.NativeStart.main(Native Me

**Comment by iRaam** [comment]
Anyone got a fix for this issue ? I am testing in a Samsung device (MarshMallow) which crashes after giving permission showing this preview failure error.

**Comment by commonsguy** [comment]
@iRaam This library has been discontinued for months. Please use another library.
