### ISSUE TITLE
Android Studio:Failed to find Dependency

### ISSUE THREAD

**Issue by meher421** [commonsguy/cwac-camera#248]
I am trying to use this library in Android Studio and trying to add gradle in gradle dependencies as

compile 'com.commonsware.cwac:camera:0.6.+'

But Android studio throws error " Failed to find : com.commonsware.cwac:camera:0.6.+".

Please fix it as soon as possible.

**Comment by commonsguy** [comment]
Closing as duplicate of issue #247
