### ISSUE TITLE
Nexus 4 crash on rotate when recording hint set to Still Only

### ISSUE THREAD

**Issue by mikescamell** [commonsguy/cwac-camera#260]
Not so much a bug but a viable workaround.

The Nexus 7 2012 needs a recording hint of "Still Only" to record videos (in my case). This setting though caused the camera to stop recording on the front camera of the Nexus 4 when rotated from landscape to portrait or vice versa.

Creating a profile for the Nexus 7 2012 can avoid this.

Profile Title: cwac_camera_profile_asus_nakasi.xml

The XML:

```xml
<!--Nexus 7 2012-->
<deviceProfile>
      <recordingHint>
          STILL_ONLY
      </recordingHint>
</deviceProfile>
```

**Comment by commonsguy** [comment]
I'm pretty sure that I was able to record videos on the 2012 Nexus 7 without `STILL_ONLY`. What were your symptoms?

**Comment by mscamell** [comment]
It would freeze as soon as the camera was started.

**Comment by commonsguy** [comment]
@mikescamell Sorry, but I cannot reproduce your problem. I have no difficulty recording videos using the demo app on a Nexus 7 2012 running Android 5.1. Can you reproduce this using the demo app?

**Comment by mikescamell** [comment]
I'll give it a go when i'm at work, but this honestly solved the issue i was having with it. It could obviously be due to my setup of your library.

**Comment by mikescamell** [comment]
I forgot, a colleague who was also having an issue with the Nexus 7 2012 also had to set it to STILL_ONLY.

**Comment by commonsguy** [comment]
@mikescamell It's also possible that the problem manifests on Android 5.0 (or something else the Nexus 7 2012 used to have) and not on 5.1. You're welcome to leave your fix in place, of course. I'm just hesitant to change the library to include this fix without having reproduced the problem.

**Comment by mikescamell** [comment]
Completely understandable :)

My Nexus 2012 has been updated to 5.1 so i'll give it a go when i get a chance and get back to you.

**Comment by mikescamell** [comment]
@commonsguy finally got a chance to test the Nexus 7 on 5.1.1. I could start and stop video recording but no videos seem to have been saved to the device and would occasionally get "stop failed" messages along with "Attempt to invoke virtual method 'void android.media.MediaRecorder.stop()' on a null object reference.

**Comment by commonsguy** [comment]
@mikescamell I cannot reproduce your problem. On a Nexus 7 (2012) running Android 5.1.1, in landscape, I can record videos off of the FFC without issue using the `demo/` app. I am having difficulty seeing them via MTP (i.e., mounting external storage as a drive or volume), but they are there when viewed using **`adb shell ls /mnt/shell/emulated/0/Movies`** and the Android Device Monitor's file explorer.

**Comment by mikescamell** [comment]
Sorry @commonsguy i didn't realise vids were being stored in Movies, expected to see them in DCIM. Videos are in there but obviously that doesn't explain the errors i was getting above. First recording seems to work fine, but i get the previous messages on subsequent records/stops. 

As to my `STILL_ONLY` issues, as you mentioned before it's obviously not worth implementing them if you and i both can record without freezing. I guess it must have been something i was setting in my CameraHost that was causing the issue. I'd look into it more but unfortunately i'm in the middle of a large project at work.

Apologies for wasting your time.

**Comment by commonsguy** [comment]
@mikescamell 

> First recording seems to work fine, but i get the previous messages on subsequent records/stops. 

I did two recordings in succession and did not crash. Now, it's possible that I did something between those two recordings that somehow changed matters and therefore did not trigger the bug.

> I'd look into it more but unfortunately i'm in the middle of a large project at work.

No worries. If you come up with steps to reproduce the crash, comment here and I can reopen the issue.
