### ISSUE TITLE
Workaround/Fix for corrupted images on some devices

### ISSUE THREAD

**Issue by shemarlindie** [commonsguy/cwac-camera#262]
After reading <a href="http://stackoverflow.com/questions/12148675/issue-with-samsung-galaxy-siii-camera-onpicturetaken-returning-interlaced-im/14943940#14943940">this</a> I decided to take a look at the cwac-camera source to see where the picture size was set. As expected, it is set after the preview is started which causes the image corruption bug on some devices because of the reason stated the the linked answer, I presume. 

To avoid this I found a window just before the preview is started to set the picture parameters without modifying the source. This is what I did:

<pre>
@Override
public Camera.Parameters adjustPreviewParameters(Camera.Parameters parameters) {
        Log.d(TAG, "adjustPreviewParameters()");
        // Workaround: set picture parameters before preview starts to prevent image corruption bug
        Camera.Size size = getPictureSize(null, parameters);
        parameters.setPictureSize(size.width, size.height);
        parameters.setPictureFormat(ImageFormat.JPEG);
        parameters.setJpegQuality(85);
        parameters.setJpegThumbnailQuality(85);
        return parameters;
}
</pre>

In the source, <code>adjustPreviewParameters()</code> is called right before the preview is started, since you have access to the camera parameters at this point you can set your picture parameters in there. Just extend <code>SimpleCameraHost</code> and override the method like above.

I can confirm this works on the Samsung Galaxy S3 (samsung_d2tmo).

@commonsguy correct me if I'm wrong or if this is a bad fix.

**Comment by commonsguy** [comment]
@shemarlindie I see nothing intrinsically wrong with what you're doing. The larger issue of adjusting parameters at wrong times is why I am rebooting this library. But, if this helps you with compatibility in your scenario, you're certainly welcome to roll with it.

**Comment by shemarlindie** [comment]
Great! Glad to hear it.
All the best with the reboot.
