### ISSUE TITLE
Rotated pictures on version 0.6.12

### ISSUE THREAD

**Issue by Odunayo16** [commonsguy/cwac-camera#263]
Everyone once in awhile when taking a picture on Nexus 5, Galaxy S4/S5, LG G2, the picture that is taken is rotated. The bug has been hard to reproduce and occurs randomly maybe every 1/100 photos.

**Comment by commonsguy** [comment]
@Odunayo16: Does this occur only when taking pictures in portrait mode?

**Comment by Odunayo16** [comment]
The application is locked to portrait mode in the mainactivity

**Comment by commonsguy** [comment]
Then you are probably running into an `OutOfMemoryError`, causing me to bail out of the attempt to rotate the image. There is nothing really that I can do about this. Adding `android:largeHeap="true"` to your manifest will help, or use `maxPictureCleanupHeapUsage()` to control matters a bit more. See [the documentation](https://github.com/commonsguy/cwac-camera#fixing-up-images-and-your-heap) for details.

If you have evidence that this is *not* tied to running out of memory, let me know, and I can reopen the issue.

**Comment by Odunayo16** [comment]
Yeah its definitely due to running out of memory. I already have android:largeHeap="true" in my manifest. Is there a way to make it so that it takes the correct picture in portrait without having to rotate?

**Comment by commonsguy** [comment]
@Odunayo16: By definition, if I have to rotate it, it did not take the correct picture in portrait. Some cameras do. Others do not, preferring to just set the EXIF header to ask the client to rotate it. What I try to do is normalize the photos, rotating the ones that were not rotated by the camera. However, that is memory-intensive for high-resolution photos. Eventually, I'll work up some NDK-based solution, which would avoid the Dalvik heap limit. That will probably be for the next-generation library, though.

**Comment by Odunayo16** [comment]
Ah I see. Would it make sense then to just create a custom device profile which overrides useDeviceOrientation in order to get a standardized orientation on all phones?

**Comment by commonsguy** [comment]
@Odunayo16 That won't give you a standardized orientation on all phones. If it did, I wouldn't need all this image-rotation stuff. If you want to disable the image rotation, have `maxPictureCleanupHeapUsage()` return `0.0f`, as noted in [the documentation](https://github.com/commonsguy/cwac-camera#fixing-up-images-and-your-heap).

**Comment by Odunayo16** [comment]
I figured out what the problem was. I think I was not resetting the camera preview correctly so on subsequent calls it eventually ran out of memory. Thank you for your help!
