### ISSUE TITLE
onFaceDetection never called again after taking picture on multishoot mode

### ISSUE THREAD

**Issue by Hallaz** [commonsguy/cwac-camera#273]
Fist at all, thanks so much for the guy behind commonsWare.

its my first time using cwac camera libs.
im trying to build a camera apps tht automatically taking picture if it detecting people face.
at the first attempt it working well, but AFTER taking a picture and got some byte[] data at @Override public void saveImage(...) the face detection listener (onFaceDetection ) never called again. I tried call startFaceDetection() but got no effect.

is any other way to startFaceDetection, i mean the onFaceDetection method called again after taking a picture?

sorry for my bad english..

Thank you so much.

**Comment by commonsguy** [comment]
You can try calling `stopFaceDetection()`, followed by `startFaceDetection()`, to try to get it to "reboot" the face detection logic. If that does not help, I would need you to publish a sample app that exhibits the problem that you are seeing. I am unconvinced that there is much that I can do about the issue, but without code to reproduce the problem, there is nothing at all that I can do.

**Comment by Hallaz** [comment]
Problem solved...
Thank you :)

By restarting faceDetection solve the problem.
  
=> You can try calling stopFaceDetection(), followed by startFaceDetection()

**Comment by commonsguy** [comment]
This library is not supported.
