### ISSUE TITLE
Captured image is not storing on MediaStore

### ISSUE THREAD

**Issue by ShreyashPromact** [commonsguy/cwac-camera#277]
I have capture image using this library. But after that i have code to retrieve all the images of the MediaStore. I get all the images but not the captured one. please let me know if i need to update anything more.

**Comment by commonsguy** [comment]
The library does not use `MediaScannerConnection` or anything else to index your images. You will need to arrange to do that yourself.

**Comment by ShreyashPromact** [comment]
But at least suggest me for how to add it in to the MediaStore. Because i have try a lot with the code available on developer blog and on SO but i am not getting success on it. I need suggestion from you regarding it, if you can do.

**Comment by commonsguy** [comment]
This is an issue tracker for a library. It is not a general-purpose Android support board, for questions about how to use `MediaScannerConnection`. There are [many of those sites, in a variety of languages](http://www.andglobe.com).

**Comment by ShreyashPromact** [comment]
Ok Thanks for reply. :)
