### ISSUE TITLE
Back camera not working on s3 4.4.2

### ISSUE THREAD

**Issue by cvofjaspreet** [commonsguy/cwac-camera#279]
Hi,

Back camera not working on  s3 4.4.2. It just show black screen.

It works on all my devices other then this. Even I have 1 more s3 with os version 4.3 and it works. Can you please guild be what can be issue for that particular device.

Jaspreet

**Comment by commonsguy** [comment]
There are many devices named "s3". I need the `Build.MANUFACTURER` and `Build.PRODUCT` values, so I can see if I have the same device.

**Comment by cvofjaspreet** [comment]
Hi,

Thanks for the quick reply.

Device is with my client, can't get that grammatically. But here are screen
shots of about phone.

https://dl.pushbulletusercontent.com/sBTD3MwIyX02j1fJagTWjBLWdOkBBokA/Screenshot_2015-05-12-11-17-03.png

https://dl.pushbulletusercontent.com/4ZIxjFqddX3QSosu89Wqa2sFwjNK9QYC/Screenshot_2015-05-12-11-17-22.png

Note: Problem is with back camera only, front camera is fine.

Jas

On Wed, May 13, 2015 at 4:12 PM, Mark Murphy <notifications@github.com>
wrote:

> There are many devices named "s3". I need the Build.MANUFACTURER and
> Build.PRODUCT values, so I can see if I have the same device.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/commonsguy/cwac-camera/issues/279#issuecomment-101620002>
> .
>



--

**Comment by commonsguy** [comment]
If, at some point, you can find out the manufacturer and product name, please update the issue. Without that information, there is nothing that I can do for you.

**Comment by cvofjaspreet** [comment]
Hi Mark,

I got the details :

Build.MANUFACTURER : samsung

Build.PRODUCT : d2lterefreshspr

Jaspreet


On Wed, May 13, 2015 at 6:56 PM, Mark Murphy <notifications@github.com>
wrote:

> If, at some point, you can find out the manufacturer and product name,
> please update the issue. Without that information, there is nothing that I
> can do for you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/commonsguy/cwac-camera/issues/279#issuecomment-101663218>
> .
>



--

**Comment by commonsguy** [comment]
OK, I definitely do not have one of those. I should be able to run some tests on one in about 10 days.

**Comment by ErnestG** [comment]
@cvofjaspreet is that with the demo application or your application?

**Comment by cvofjaspreet** [comment]
Thanks Mark.

@ErnestG  Its on both .

Jaspreet

**Comment by cvofjaspreet** [comment]
Hi Guys,

Its just to reminder , I know 4 days left . It will be very helpful for me if can be done early.

Jas

**Comment by cvofjaspreet** [comment]
Hi Guys,

10 days are past any update for me ?

Jas

**Comment by commonsguy** [comment]
I cannot reproduce your problem, using a Samsung Galaxy S3 SPH-L710T running Android 4.4.2. The demo app preview and pictures work fine with the rear-facing camera and the front-facing camera, in portrait and landscape.

If you wish, post a comment on this question that provides **complete and precise steps** for reproducing this problem with the demo app. If I can reproduce the problem using those steps, I will reopen this issue.
