### ISSUE TITLE
Preview Image in incorrect orientation

### ISSUE THREAD

**Issue by rohanmahale** [commonsguy/cwac-camera#282]
Project : The demo app that is part of this project.
Test Device : Nexus 5.

Steps To reproduce bug of incorrectly rotated preview

1. Start app.
2. Check Single-Shot Mode
3. Take Pic..Check Preview . Preview is Correct.
4. Uncheck Single-Shot mode.
5. Take Pic.
6. Check Single-Shot Mode again.
7. Take Pic. Check Preview..Preview is rotated by 90 degrees.

**Comment by commonsguy** [comment]
I can reproduce the effect if the device is in portrait mode, on a Nexus 5 running Android 5.1. Most likely, I am running out of memory and cannot do the image rotation based on the EXIF tags. Rotating the image to normalize the output is attempted but not guaranteed. That being said, I'll keep this issue in mind as I work on the replacement library.

**Comment by rohanmahale** [comment]
Oh okay. Thanks. Will there be a fix for this lib?

**Comment by commonsguy** [comment]
No, there will not.

**Comment by rohanmahale** [comment]
Hi Mark. If my camera activity is fixed in the portrait orientation, but I need the output image (preview) to be in portrait no matter which orientation the phone is in while taking the picture, what do I need to do?

**Comment by rohanmahale** [comment]
I'm sorry to have bothered you Mike. I figured it out.
