### ISSUE TITLE
takePicture - Freeze on S3 Android 4.4.4

### ISSUE THREAD

**Issue by kingdata18** [commonsguy/cwac-camera#286]
Hi,

I've being try to get a workaround for this issue on my phone for the last days, but still no success.

Steps to reproduce:

1. Deployed on my phone the "demo" app.
2. Open app and press "takePicture" icon.
3. App/camera freezes right after "camera.setParameters(xact.host.adjustPictureParameters(xact,
pictureParams));" on CameraView.java, looks like it falls into a loop hole, and camera api doesn't return or throw exception.

Btw, the native camera app works fine taking shots.

My phone specs (CyanogenMod installed):

Model: GT-I9300 (Samsung S3)
CyanogenMod Version: 11-20150706-NIGHTLY-i9300
Android Version: 4.4.4

**Comment by kingdata18** [comment]
Correction:

It actually freezes on "camera.setParameters(xact.host.adjustPictureParameters(xact,
                                                               pictureParams));", looks like it falls into a loop hole, and camera api doesn't return or throw exception.

**Comment by commonsguy** [comment]
This is probably another example of the overall "can't change `Camera.Parameters` safely on the fly" problem that plagues this library and is why I am rewriting it. While a 0.1 of the CWAC-Cam2 library will (hopefully) be released next week, it has a substantially reduced API footprint. If you are looking for a simple `ACTION_IMAGE_CAPTURE` replacement, CWAC-Cam2 will be a possible solution. If you are looking for more than that, my only recommendation is to code to the Android camera APIs yourself.

**Comment by kingdata18** [comment]
I am a big fan of your work and I'll surely wait for the CWAC-Cam2!
Thanks!
