### ISSUE TITLE
always throws java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by CaiHuan** [commonsguy/cwac-camera#288]
07-29 16:09:29.717   6730-13306/com.zshd.baby W/System.err﹕ java.lang.OutOfMemoryError
07-29 16:09:29.727   6730-13306/com.zshd.baby W/System.err﹕ at android.graphics.Bitmap.nativeCreate(Native Method)
07-29 16:09:29.727   6730-13306/com.zshd.baby W/System.err﹕ at android.graphics.Bitmap.createBitmap(Bitmap.java:726)
07-29 16:09:29.727   6730-13306/com.zshd.baby W/System.err﹕ at android.graphics.Bitmap.createBitmap(Bitmap.java:703)
07-29 16:09:29.727   6730-13306/com.zshd.baby W/System.err﹕ at android.graphics.Bitmap.createBitmap(Bitmap.java:636)
07-29 16:09:29.727   6730-13306/com.zshd.baby W/System.err﹕ at com.commonsware.cwac.camera.ImageCleanupTask.run(ImageCleanupTask.java:127)

[ro.opengles.version]: [196608]
[ro.product.board]: [MSM8928]
[ro.product.brand]: [samsung]
[ro.product.cpu.abi2]: [armeabi]
[ro.product.cpu.abi]: [armeabi-v7a]
[ro.product.device]: [hllte]
[ro.product.locale.language]: [zh]
[ro.product.locale.region]: [CN]
[ro.product.manufacturer]: [samsung]
[ro.product.model]: [SM-N7506V]

**Comment by commonsguy** [comment]
[Stop using the library](https://github.com/commonsguy/cwac-camera).

Or, [adjust your `maxPictureCleanupHeapUsage()` value returned by your `CameraHost`](https://github.com/commonsguy/cwac-camera/blob/master/README-original.markdown#fixing-up-images-and-your-heap). If you have this return `0.0f`, you should not run out of memory in `ImageCleanupTask`, though it means that your image will not be adjusted to take into account things like EXIF orientation headers.
