### ISSUE TITLE
Conitnuous autofocus in camera

### ISSUE THREAD

**Issue by millas11** [commonsguy/cwac-camera#289]
Hi, I would like avoid force to press any button to do autofocus when i take a photo. The first possibility was do autofocus() and next takePhoto, but throw exception.

How can do any similar action?

Thank you!

**Comment by commonsguy** [comment]
Please read [the project `README`](https://github.com/commonsguy/cwac-camera) about the status of the library, and the [instructions for asking questions](https://github.com/commonsguy/cwac-camera/blob/master/README-original.markdown#questions).

I have no idea how to do anything of what you are describing, sorry.
