### ISSUE TITLE
Images Orientation automatically change after clicking one image

### ISSUE THREAD

**Issue by Priyankbhojak88** [commonsguy/cwac-camera#290]
I am using your library which is very helpful to create custom camera but I am facing issue after taking multiple images.I have also checked your demos,in that image orientation is proper after taking pic as you are displaying image in new activity.I am using takeSimplePicture() method from your demo to capture image.

In my case I have to show all captured images on same screen but only first image set in correct orientation all other are getting rotate in landscape mode.I am using Nexus 5(5.1.1) device.and also sharing screen shoot for the same.

ScreenShoot:

Check Top images list from below screen shoot only first image is in Portrait and all other are in landscape.I am taking all pics in portrait mode.

![image_capture](https://cloud.githubusercontent.com/assets/14315443/9911411/9efbaa8a-5cbf-11e5-91db-4b8179307d12.png)

**Comment by commonsguy** [comment]
My guess is that you do not have enough memory, and the image-rotation task is not being run on the second and subsequent pictures. If you have not done so already, add `android:largeHeap="true"` to your manifest and see if that helps.

Beyond that, no further work is being done on this library. My [replacement library](https://github.com/commonsguy/cwac-cam2) does not handle changing the orientation yet, but when it does, it will use C/C++ code, to avoid Dalvik heap limit issues.

**Comment by sagaratalatti** [comment]
I have tried adding android:uselargeheap=true for both cameraActivity and Application.

**Comment by sagaratalatti** [comment]
But still the images rotate.

**Comment by commonsguy** [comment]
This library has been discontinued.
