### ISSUE TITLE
Preview Image is not shown 5.0.2 (Moto G, Samsung S5)

### ISSUE THREAD

**Issue by spirosoik** [commonsguy/cwac-camera#292]
I can take a picture but the camera doesn't keep the image. I have single shot true. I am using Camera activity with a custom fragment which includes a cameraview.

**Comment by commonsguy** [comment]
[This library is no longer supported](https://github.com/commonsguy/cwac-camera/blob/master/README-original.markdown#questions).

**Comment by spirosoik** [comment]
@commonsguy ok thanks.
