### ISSUE TITLE
On some scenario I am getting this (Sorry, but you cannot use the camera now!) error. 

### ISSUE THREAD

**Issue by Vijayadhas** [commonsguy/cwac-camera#293]
Hi,

   Some time when I open the camera It showing blank and show this toast message.
Sorry, but you cannot use the camera now!. After than I can not use the app. I can only use the app after restart my mobile. 

I come to know that the problem is happening at call back. But I can not resolve the issue. 

Please let me any idea to resolve this,

**Comment by commonsguy** [comment]
This library has been discontinued and is no longer supported.
