### ISSUE TITLE
how to controll flash light?

### ISSUE THREAD

**Issue by gepriniusce** [commonsguy/cwac-camera#294]
how to controll flash light?~~~My phone is Galaxy S4.
Use Demo the flash light doesn't work.

PictureTransaction xact = new PictureTransaction(getCameraHost());

        if (flashItem != null && flashItem.isChecked()) {
            xact.flashMode(flashMode);
        }

        takePicture(xact);

Even though this flashMode=on ，but the flash light doesn't work.

**Comment by commonsguy** [comment]
@gepriniusce This library is discontinued.
