### ISSUE TITLE
Issues resolving dependency 

### ISSUE THREAD

**Issue by traviswestbrook** [commonsguy/cwac-camera#295]
I cleared my .gradle cache and now when I try pull down v 0.7.0 I get the following error.

 ```
Could not download camera.aar (com.commonsware.cwac:camera:0.7.0)
      > Could not get resource 'https://repo.commonsware.com.s3.amazonaws.com/com/commonsware/cwac/camera/0.7.0/camera-0.7.0.aar'.
         > Could not GET 'https://repo.commonsware.com.s3.amazonaws.com/com/commonsware/cwac/camera/0.7.0/camera-0.7.0.aar'.
            > Host name 'repo.commonsware.com.s3.amazonaws.com' does not match the certificate subject provided by the peer (CN=*.s3.amazonaws.com, O=Amazon.com Inc., L=Seattle, ST=Washington, C=US)
```

**Comment by commonsguy** [comment]
Note that this project is discontinued.

It looks like Amazon is having a problem with their SSL certificate. You will need to downgrade to `http` instead of `https` for the scheme until this gets worked out.

**Comment by traviswestbrook** [comment]
thanks!

**Comment by commonsguy** [comment]
BTW, I forgot that I had changed the repo syntax a while ago to deal with this problem. If you check [the docs](https://github.com/commonsguy/cwac-camera/blob/master/README-original.markdown), you will see that I now advise you to use `https://s3.amazonaws.com/repo.commonsware.com`.
