### ISSUE TITLE
video is not saving in android cwac

### ISSUE THREAD

**Issue by shankarpilli** [commonsguy/cwac-camera#296]
Hi, 

I am using **compile 'com.commonsware.cwac:camera:0.6.2'** . For my video i wrote simply 

case R.id.img_video:
                try {
                    Utility.showLog("Vieo called","video called");
                    mCameraView.record();
                } catch (Exception e) {
                    e.printStackTrace();
                }
                break;
            case R.id.img_stopcame:
                try {
                    mCameraView.stopRecording();
                } catch (IOException e) {
                    e.printStackTrace();
                }
                break;

I have take all the three permissions. 

When i click stop i got **MediaRecorder: mediarecorder went away with unhandled events** 

please help me

**Comment by commonsguy** [comment]
As is noted in [the documentation](https://github.com/commonsguy/cwac-camera/blob/master/README-original.markdown#questions), this library is no longer supported. As is noted on [the project home page](https://github.com/commonsguy/cwac-camera), please use some other library.

**Comment by shankarpilli** [comment]
If i want to use portrait video recording which i have to use. ?
