### ISSUE TITLE
Why cannot parse this image?

### ISSUE THREAD

**Issue by RandyPanGit** [commonsguy/cwac-camera#297]
Why cannot parse  this image?

[image](https://mega.nz/#!wtkXibDD!RI9QScpxsRNyO4shgpwnJwCzr7AB4gcGsRB9YUs9u8k)

**Comment by commonsguy** [comment]
As is noted in [the documentation](https://github.com/commonsguy/cwac-camera/blob/master/README-original.markdown#questions), this library is no longer supported. As is noted on [the project home page](https://github.com/commonsguy/cwac-camera), please use some other library.
