### ISSUE TITLE
Does not capture Photo in moto g 

### ISSUE THREAD

**Issue by dilipbirajadar** [commonsguy/cwac-camera#298]
It Showing this error  

W/CameraBase: An error occurred while connecting to camera: 0
05-13 12:46:41.289 9989-9989/com.cybit.linkwok E/CWAC-Camera: Camera access failed: 2

**Comment by commonsguy** [comment]
This library has been discontinued.

**Comment by dilipbirajadar** [comment]
Which library is available for this

**Comment by commonsguy** [comment]
Quoting the project `README`: "Options include:

- Various other [open source camera libraries for Android](http://android-arsenal.com/tag/141)
- [CWAC-Cam2](https://github.com/commonsguy/cwac-cam2), the author's second attempt at a camera library
- using the Android SDK APIs (`Camera` and `android.hardware.camera2.*`) directly"

**Comment by dilipbirajadar** [comment]
Thanks...
